### ISSUE TITLE
error: ‘begin’ was not declared in this scope

### ISSUE THREAD

**Issue by Luolijie97** [ferasboulala/staff-detect#1]
I followed the installation instructions：
$ git clone https://github.com/ferasboulala/staff-detect.git
$ cd staff-detect && mkdir bin build
$ cd build && cmake ..
$ cd ../bin && ./stav --help

But there is no stav file in bin，So I executed the following code in the build folder:
$ make
Then the following error occurred:

[ 20%] Building CXX object CMakeFiles/stav.dir/src/stav.cc.o
/home/cy/llj/staff-detect/src/stav.cc: In function ‘void delegate_tasks(GlobalRequest)’:
/home/cy/llj/staff-detect/src/stav.cc:90:46: error: ‘begin’ was not declared in this scope
     for (auto &p : fs::directory_iterator(out))
                                              ^
/home/cy/llj/staff-detect/src/stav.cc:90:46: note: suggested alternatives:
In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/string:51:0,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/stdexcept:39,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/array:39,
                 from /usr/local/include/opencv2/core/cvdef.h:438,
                 from /usr/local/include/opencv2/core.hpp:52,
                 from /usr/local/include/opencv2/opencv.hpp:52,
                 from /home/cy/llj/staff-detect/include/staff.hh:4,
                 from /home/cy/llj/staff-detect/src/stav.cc:1:
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/range_access.h:105:37: note:   ‘std::begin’
   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
                                     ^~~~~
In file included from /usr/include/boost/range/functions.hpp:18:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:26,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/range/begin.hpp:112:61: note:   ‘boost::range_adl_barrier::begin’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type begin( const T& r )
                                                             ^~~~~
In file included from /usr/include/boost/mpl/list/aux_/begin_end.hpp:17:0,
                 from /usr/include/boost/mpl/list/list0.hpp:27,
                 from /usr/include/boost/mpl/list/list10.hpp:18,
                 from /usr/include/boost/mpl/list/list20.hpp:18,
                 from /usr/include/boost/mpl/list.hpp:36,
                 from /usr/include/boost/math/policies/policy.hpp:9,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:28,
                 from /usr/include/boost/math/special_functions/sign.hpp:17,
                 from /usr/include/boost/lexical_cast.hpp:167,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/mpl/begin_end_fwd.hpp:22:38: note:   ‘boost::mpl::begin’
 template< typename Sequence > struct begin;
                                      ^~~~~
In file included from /usr/include/boost/range/functions.hpp:18:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:26,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/range/begin.hpp:112:61: note:   ‘boost::range_adl_barrier::begin’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type begin( const T& r )
                                                             ^~~~~
/home/cy/llj/staff-detect/src/stav.cc:90:46: error: ‘end’ was not declared in this scope
     for (auto &p : fs::directory_iterator(out))
                                              ^
/home/cy/llj/staff-detect/src/stav.cc:90:46: note: suggested alternatives:
In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/string:51:0,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/stdexcept:39,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/array:39,
                 from /usr/local/include/opencv2/core/cvdef.h:438,
                 from /usr/local/include/opencv2/core.hpp:52,
                 from /usr/local/include/opencv2/opencv.hpp:52,
                 from /home/cy/llj/staff-detect/include/staff.hh:4,
                 from /home/cy/llj/staff-detect/src/stav.cc:1:
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/range_access.h:107:37: note:   ‘std::end’
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
In file included from /usr/include/boost/range/functions.hpp:19:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:26,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/range/end.hpp:106:61: note:   ‘boost::range_adl_barrier::end’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type end( const T& r )
                                                             ^~~
In file included from /usr/include/boost/mpl/list/aux_/begin_end.hpp:17:0,
                 from /usr/include/boost/mpl/list/list0.hpp:27,
                 from /usr/include/boost/mpl/list/list10.hpp:18,
                 from /usr/include/boost/mpl/list/list20.hpp:18,
                 from /usr/include/boost/mpl/list.hpp:36,
                 from /usr/include/boost/math/policies/policy.hpp:9,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:28,
                 from /usr/include/boost/math/special_functions/sign.hpp:17,
                 from /usr/include/boost/lexical_cast.hpp:167,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/mpl/begin_end_fwd.hpp:23:38: note:   ‘boost::mpl::end’
 template< typename Sequence > struct end;
                                      ^~~
In file included from /usr/include/boost/range/functions.hpp:19:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:26,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/range/end.hpp:106:61: note:   ‘boost::range_adl_barrier::end’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type end( const T& r )
                                                             ^~~
/home/cy/llj/staff-detect/src/stav.cc:97:45: error: ‘begin’ was not declared in this scope
     for (auto &p : fs::directory_iterator(in))
                                             ^
/home/cy/llj/staff-detect/src/stav.cc:97:45: note: suggested alternatives:
In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/string:51:0,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/stdexcept:39,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/array:39,
                 from /usr/local/include/opencv2/core/cvdef.h:438,
                 from /usr/local/include/opencv2/core.hpp:52,
                 from /usr/local/include/opencv2/opencv.hpp:52,
                 from /home/cy/llj/staff-detect/include/staff.hh:4,
                 from /home/cy/llj/staff-detect/src/stav.cc:1:
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/range_access.h:105:37: note:   ‘std::begin’
   template<typename _Tp> const _Tp* begin(const valarray<_Tp>&);
                                     ^~~~~
In file included from /usr/include/boost/range/functions.hpp:18:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:26,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/range/begin.hpp:112:61: note:   ‘boost::range_adl_barrier::begin’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type begin( const T& r )
                                                             ^~~~~
In file included from /usr/include/boost/mpl/list/aux_/begin_end.hpp:17:0,
                 from /usr/include/boost/mpl/list/list0.hpp:27,
                 from /usr/include/boost/mpl/list/list10.hpp:18,
                 from /usr/include/boost/mpl/list/list20.hpp:18,
                 from /usr/include/boost/mpl/list.hpp:36,
                 from /usr/include/boost/math/policies/policy.hpp:9,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:28,
                 from /usr/include/boost/math/special_functions/sign.hpp:17,
                 from /usr/include/boost/lexical_cast.hpp:167,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/mpl/begin_end_fwd.hpp:22:38: note:   ‘boost::mpl::begin’
 template< typename Sequence > struct begin;
                                      ^~~~~
In file included from /usr/include/boost/range/functions.hpp:18:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:26,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/range/begin.hpp:112:61: note:   ‘boost::range_adl_barrier::begin’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type begin( const T& r )
                                                             ^~~~~
/home/cy/llj/staff-detect/src/stav.cc:97:45: error: ‘end’ was not declared in this scope
     for (auto &p : fs::directory_iterator(in))
                                             ^
/home/cy/llj/staff-detect/src/stav.cc:97:45: note: suggested alternatives:
In file included from /opt/rh/devtoolset-7/root/usr/include/c++/7/string:51:0,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/stdexcept:39,
                 from /opt/rh/devtoolset-7/root/usr/include/c++/7/array:39,
                 from /usr/local/include/opencv2/core/cvdef.h:438,
                 from /usr/local/include/opencv2/core.hpp:52,
                 from /usr/local/include/opencv2/opencv.hpp:52,
                 from /home/cy/llj/staff-detect/include/staff.hh:4,
                 from /home/cy/llj/staff-detect/src/stav.cc:1:
/opt/rh/devtoolset-7/root/usr/include/c++/7/bits/range_access.h:107:37: note:   ‘std::end’
   template<typename _Tp> const _Tp* end(const valarray<_Tp>&);
                                     ^~~
In file included from /usr/include/boost/range/functions.hpp:19:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:26,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/range/end.hpp:106:61: note:   ‘boost::range_adl_barrier::end’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type end( const T& r )
                                                             ^~~
In file included from /usr/include/boost/mpl/list/aux_/begin_end.hpp:17:0,
                 from /usr/include/boost/mpl/list/list0.hpp:27,
                 from /usr/include/boost/mpl/list/list10.hpp:18,
                 from /usr/include/boost/mpl/list/list20.hpp:18,
                 from /usr/include/boost/mpl/list.hpp:36,
                 from /usr/include/boost/math/policies/policy.hpp:9,
                 from /usr/include/boost/math/special_functions/math_fwd.hpp:28,
                 from /usr/include/boost/math/special_functions/sign.hpp:17,
                 from /usr/include/boost/lexical_cast.hpp:167,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/mpl/begin_end_fwd.hpp:23:38: note:   ‘boost::mpl::end’
 template< typename Sequence > struct end;
                                      ^~~
In file included from /usr/include/boost/range/functions.hpp:19:0,
                 from /usr/include/boost/range/iterator_range_core.hpp:26,
                 from /usr/include/boost/lexical_cast.hpp:169,
                 from /usr/include/boost/program_options/value_semantic.hpp:14,
                 from /usr/include/boost/program_options/options_description.hpp:13,
                 from /usr/include/boost/program_options.hpp:15,
                 from /home/cy/llj/staff-detect/src/stav.cc:6:
/usr/include/boost/range/end.hpp:106:61: note:   ‘boost::range_adl_barrier::end’
 inline BOOST_DEDUCED_TYPENAME range_iterator<const T>::type end( const T& r )
                                                             ^~~
make[2]: *** [CMakeFiles/stav.dir/src/stav.cc.o] error 1
make[1]: *** [CMakeFiles/stav.dir/all] error 2
make: *** [all] error 2

Can you tell me how to compile this project correctly？

**Comment by kyrieb-ekat** [comment]
Hi, I'm also having this problem, was a resolution ever found? It appears some version of Boost may no longer be compatible?
